spring:
  profiles:
    active: dev
  mandatory-file-encoding: UTF-8
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
mybatis:
  mapper-locations: mapper/*Mapper.xml
  type-aliases-package: com.horaoen.sailor.web.model
  config-location: classpath:config/mybatis-config.xml

sailor:
  cms:
    # 开启行为日志记录（logger）
    logger-enabled: true
    # access token 过期时间，3600s 一个小时
    token-access-expire: 3600
    # refresh token 过期时间，2592000s 一个月
    token-refresh-expire: 2592000
    # 令牌 secret
    token-secret: x88Wf0991079889x8796a0Ac68f9ecJJU17c5Vbe8beod7d8d3e695*4
auth:
  enabled: true