spring:
  devtools:
    restart:
      enabled: true
  mvc:
    log-request-details: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: Horaoen@624
    url: jdbc:mysql://42.192.5.249:3306/sailor?useSSL=false&serverTimezone=UTC&characterEncoding=UTF8
    username: root

springdoc:
  packages-to-scan: com.horaoen.sailor.web.controller
  
logging:
  level:
    web: debug